package dev.vality.disputes.provider.payments.exception;

public class ProviderCallbackAlreadyExistException extends RuntimeException {
}
